language: go
script: go get -v && go test -v && go build -o $TRAVIS_BUILD_DIR/WhatIsMyIp
before_deploy:
  - echo $(ls $TRAVIS_BUILD_DIR)
deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file: "$TRAVIS_BUILD_DIR/WhatIsMyIp"
  skip_cleanup: true
  on:
    tags: true
