language: go
script: go get -v && go test -v && go build
before_deploy:
  - export RELEASE_PKG_FILE=$(ls $TRAVIS_BUILD_DIR/*)
  - echo "Generated files= $RELEASE_PKG_FILE"
deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file: "$TRAVIS_BUILD_DIR/WhatIsMyIp"
  skip_cleanup: true
  on:
    tags: true
